export let statsList = [
  {
    'word': 'red',
    'translation': 'красный',
    'category': 'Colors',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'green',
    'translation': 'зеленный',
    'category': 'Colors',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'blue',
    'translation': 'синий',
    'category': 'Colors',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'black',
    'translation': 'черный',
    'category': 'Colors',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'purple',
    'translation': 'фиолетовый',
    'category': 'Colors',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'pink',
    'translation': 'розовый',
    'category': 'Colors',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'brown',
    'translation': 'коричневый',
    'category': 'Colors',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'yellow',
    'translation': 'желтый',
    'category': 'Colors',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  
  {
    'word': 'football',
    'translation': 'футбол',
    'category': 'sports',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'basketball',
    'translation': 'баскетбол',
    'category': 'sports',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'hockey',
    'translation': 'хоккей',
    'category': 'sports',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'volleyball',
    'translation': 'волейбол',
    'category': 'sports',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'gymnastics',
    'translation': 'гимнастика',
    'category': 'sports',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'tennis',
    'translation': 'теннис',
    'category': 'sports',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'boxing',
    'translation': 'бокс',
    'category': 'sports',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'biathlon',
    'translation': 'биатлон',
    'category': 'sports',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  
  {
    'word': 'father',
    'translation': 'папа',
    'category': 'family',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'mother',
    'translation': 'мама',
    'category': 'family',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'brother',
    'translation': 'брат',
    'category': 'family',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'sister',
    'translation': 'сестра',
    'category': 'family',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'grandad',
    'translation': 'дедушка',
    'category': 'family',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'granny',
    'translation': 'бабушка',
    'category': 'family',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'dog',
    'translation': 'собака',
    'category': 'family',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'cat',
    'translation': 'кот',
    'category': 'family',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  
  {
    'word': 'lion',
    'translation': 'лев',
    'category': 'animals',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'tiger',
    'translation': 'тигр',
    'category': 'animals',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'elephant',
    'translation': 'слон',
    'category': 'animals',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'squirrel',
    'translation': 'белка',
    'category': 'animals',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'hippo',
    'translation': 'бегемот',
    'category': 'animals',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'rabbit',
    'translation': 'кролик',
    'category': 'animals',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'bear',
    'translation': 'медведь',
    'category': 'animals',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'fox',
    'translation': 'лиса',
    'category': 'animals',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  
  {
    'word': 'eye',
    'translation': 'глаз',
    'category': 'body',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'hand',
    'translation': 'кисть',
    'category': 'body',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'arm',
    'translation': 'рука',
    'category': 'body',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'nose',
    'translation': 'нос',
    'category': 'body',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'foot',
    'translation': 'стопа',
    'category': 'body',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'finger',
    'translation': 'палец',
    'category': 'body',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'stomach',
    'translation': 'живот',
    'category': 'body',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'back',
    'translation': 'спина',
    'category': 'body',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  
  {
    'word': 'pizza',
    'translation': 'пицца',
    'category': 'yummy',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'ice-cream',
    'translation': 'мороженное',
    'category': 'yummy',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'jam',
    'translation': 'варенье',
    'category': 'yummy',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'cake',
    'translation': 'торт',
    'category': 'yummy',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'sweets',
    'translation': 'конфеты',
    'category': 'yummy',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'chocolate',
    'translation': 'шоколад',
    'category': 'yummy',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'waffles',
    'translation': 'вафли',
    'category': 'yummy',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'juice',
    'translation': 'сок',
    'category': 'yummy',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  
  {
    'word': 'table',
    'translation': 'стол',
    'category': 'home',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'sofa',
    'translation': 'диван',
    'category': 'home',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'chair',
    'translation': 'стул',
    'category': 'home',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'armchair',
    'translation': 'кресло',
    'category': 'home',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'lamp',
    'translation': 'лампа',
    'category': 'home',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'bed',
    'translation': 'кровать',
    'category': 'home',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'wardrobe',
    'translation': 'шкаф',
    'category': 'home',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'mirror',
    'translation': 'зеркало',
    'category': 'home',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  
  {
    'word': 'beach',
    'translation': 'пляж',
    'category': 'nature',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'field',
    'translation': 'поле',
    'category': 'nature',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'forest',
    'translation': 'лес',
    'category': 'nature',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'river',
    'translation': 'река',
    'category': 'nature',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'island',
    'translation': 'остров',
    'category': 'nature',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'waterfall',
    'translation': 'водопад',
    'category': 'nature',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'iceberg',
    'translation': 'айсберг',
    'category': 'nature',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
  {
    'word': 'mountain',
    'translation': 'гора',
    'category': 'nature',
    'train': '0',
    'correct': '0',
    'mistakes': '0',
    'percentage': '0.00',
  },
]